"""add_ingestion_tables

Revision ID: fe09d0572b96
Revises: 0b86ff37d417
Create Date: 2026-01-31 14:06:25.822138

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe09d0572b96'
down_revision: Union[str, Sequence[str], None] = '0b86ff37d417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('match',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('competition_id', sa.Integer(), nullable=False),
                    sa.Column('season_id', sa.Integer(), nullable=False),
                    sa.Column('match_date', sa.Date(), nullable=False),
                    sa.Column('home_team', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('away_team', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('home_score', sa.Integer(), nullable=False),
                    sa.Column('away_score', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['competition_id'], [
                                            'competition.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('event',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('match_id', sa.Integer(), nullable=False),
                    sa.Column('minute', sa.Integer(), nullable=False),
                    sa.Column('second', sa.Integer(), nullable=False),
                    sa.Column(
                        'type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('player_id', sa.Integer(), nullable=True),
                    sa.Column('team_id', sa.Integer(), nullable=False),
                    sa.Column('location_x', sa.Float(), nullable=True),
                    sa.Column('location_y', sa.Float(), nullable=True),
                    sa.Column('attributes', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
                    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('player', 'position',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'position',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.drop_table('event')
    op.drop_table('match')
    op.drop_table('competition')
    # ### end Alembic commands ###
